basePath: /
definitions:
  model.CashControl:
    properties:
      bread_in:
        type: number
      cash:
        type: number
      coin:
        type: number
      safe:
        type: number
      user_id:
        type: string
    type: object
  model.Item:
    properties:
      description:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  model.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  model.Menu:
    properties:
      description:
        type: string
      items:
        items:
          $ref: '#/definitions/model.Item'
        type: array
      name:
        type: string
      price:
        type: number
    type: object
  model.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  model.User:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      role:
        type: string
    type: object
host: humorous-colt-vital.ngrok-free.app
info:
  contact: {}
  description: This is a api MyFavFood
  title: Fiber API MyFavFood
  version: "1.0"
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: Login a user
      parameters:
      - description: Login credentials
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully logged in
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.Response'
      summary: Login a user
      tags:
      - Auth
  /api/auth/logout:
    post:
      consumes:
      - application/json
      description: Logout a user
      produces:
      - application/json
      responses:
        "200":
          description: Successfully logged out
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Logout a user
      tags:
      - Auth
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "201":
          description: Successfully created user
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.User'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Register a new user
      tags:
      - Auth
  /api/cashcontrol/create:
    post:
      consumes:
      - application/json
      description: Create a new cash control
      parameters:
      - description: CashControl object
        in: body
        name: cash
        required: true
        schema:
          $ref: '#/definitions/model.CashControl'
      produces:
      - application/json
      responses:
        "201":
          description: Successfully created cash control
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.CashControl'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Create a new cash control
      tags:
      - cash
  /api/cashcontrol/delete:
    delete:
      consumes:
      - application/json
      description: Delete cash control information
      parameters:
      - description: CashControl ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully deleted cash control
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.CashControl'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Delete cash control
      tags:
      - cash
  /api/cashcontrol/get:
    get:
      consumes:
      - application/json
      description: Get cash control by id
      parameters:
      - description: CashControl ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved cash control
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.CashControl'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Get cash control by id
      tags:
      - cash
  /api/cashcontrol/getall:
    get:
      consumes:
      - application/json
      description: Get all cash control
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved cash control
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.CashControl'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Get all cash control
      tags:
      - cash
  /api/cashcontrol/getbyuserid:
    get:
      consumes:
      - application/json
      description: Get cash control by user id
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved cash control
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.CashControl'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Get All cash control by user id
      tags:
      - cash
  /api/cashcontrol/update:
    put:
      consumes:
      - application/json
      description: Update CashControl information
      parameters:
      - description: CashControl object
        in: body
        name: cashControl
        required: true
        schema:
          $ref: '#/definitions/model.CashControl'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated CashControl
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.CashControl'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Update CashControl
      tags:
      - cash
  /api/menu/create:
    post:
      consumes:
      - application/json
      description: Create a new menu
      parameters:
      - description: Menu object
        in: body
        name: menu
        required: true
        schema:
          $ref: '#/definitions/model.Menu'
      produces:
      - application/json
      responses:
        "201":
          description: Successfully created menu
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Menu'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Create a new menu
      tags:
      - menu
  /api/menu/delete:
    delete:
      consumes:
      - application/json
      description: Delete a menu
      parameters:
      - description: Menu ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully deleted menu
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Delete a menu
      tags:
      - menu
  /api/menu/get:
    get:
      consumes:
      - application/json
      description: Get menu by id
      parameters:
      - description: Menu ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved menu
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Menu'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Get menu by id
      tags:
      - menu
  /api/menu/getall:
    get:
      consumes:
      - application/json
      description: Get all menus
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved all menus
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Menu'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Get all menus
      tags:
      - menu
  /api/menu/update:
    put:
      consumes:
      - application/json
      description: Update a menu
      parameters:
      - description: Menu object
        in: body
        name: menu
        required: true
        schema:
          $ref: '#/definitions/model.Menu'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated menu
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Menu'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Update a menu
      tags:
      - menu
  /api/user/delete:
    delete:
      consumes:
      - application/json
      description: Delete users information
      produces:
      - application/json
      responses:
        "200":
          description: Successfully deleted users
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.User'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Delete users
      tags:
      - users
  /api/user/get:
    get:
      consumes:
      - application/json
      description: Get users information
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved users
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.User'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Get users
      tags:
      - users
  /api/user/getall:
    get:
      consumes:
      - application/json
      description: Get all users
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved all users
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.User'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Get all users
      tags:
      - users
  /api/user/update:
    put:
      consumes:
      - application/json
      description: Update users information
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated users
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.User'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Update users
      tags:
      - users
swagger: "2.0"
